name: xlstmv2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda=11.8 #12.1
  - cuda-nvcc=11.8 #12.1
  - gxx_linux-64=11.2.0
  - pip=23.3
  - python=3.11.6
  - pytorch=2.1.0
  - pytorch-cuda=11.8 #12.1
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - cmake=3.27.6
  - pip:
      - pre-commit==3.5.0
      - reportlab==4.0.6
      - lm-eval==0.3.0
      - joypy==0.2.6
      - ipykernel==6.25.2
      - dacite==1.8.1
      - datasets==2.14.5
      - einops==0.7.0
      - ftfy==6.1.1
      - ninja==1.11.1.1
      - huggingface-hub==0.17.3
      - joblib==1.3.2
      - lightning==2.1.0
      - rich==13.6.0
      - lm-dataformat==0.0.20
      - omegaconf==2.3.0
      - sentencepiece==0.1.99
      - tokenizers==0.14.1
      - torchmetrics==0.11.4
      - tqdm==4.66.1
      - transformers==4.34.0
      - wandb==0.15.12
      - seaborn==0.13.0
      - pytest==7.4.2
      - openpyxl==3.1.2
      #     - flash-attn
      - opt_einsum==3.3.0
      - scipy==1.11.3
      - pykeops==2.1.2
      - hydra-core==1.3.2
      - torchtext==0.16.0
      # - git+https://github.com/idiap/fast-transformers@master
