name: xlstmpt240cu121
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults  # exclude this to work on leonardo
dependencies:
  - cuda=12.1
  - cuda-nvcc=12.1
  - gxx_linux-64=11.2.0
  - python=3.11
  - pip #=23.3.2
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - torchvision #=0.17.0
  - cmake #=3.28.2
  - pip:
      - einops #==0.7.0
      - opt_einsum #==3.3.0
      - transformers #==4.37.2
      - datasets #==2.16.1
      - pre-commit #==3.6.0
      - reportlab #==4.0.9
      - lm-eval #==0.4.0
      - joypy #==0.2.6
      - ipykernel #==6.29.0
      - dacite #==1.8.1
      - ftfy #==6.1.3
      - ninja #==1.11.1.1
      - huggingface-hub #==0.20.3
      - joblib #==1.3.2
      - lightning #==2.1.3
      - rich #==13.7.0
      - lm-dataformat #==0.0.20
      - omegaconf #==2.3.0
      - sentencepiece #==0.1.99
      - tokenizers #==0.15.1
      - torchmetrics #==1.3.0
      - tqdm #==4.66.1
      - wandb #==0.16.2
      - seaborn #==0.13.2
      - pytest #==8.0.0
      - pytest-xdist #==3.5.0
      - openpyxl #==3.1.2
      - gitpython #==3.1.41
      - scipy #==1.12.0
      - pykeops #==2.2.1
      - hydra-core #==1.3.2
      - torchtext #==0.16.2
      - tensorboard #==2.15.1
      - cryptography #==42.0.2
      - tensorflow

      # Please install by hand
      # - packaging
      # - mamba-ssm #==1.0.1
      # - causal-conv1d #==1.1.1
      # - git+https://github.com/idiap/fast-transformers@master
      # - flash-attn
